=== Hema-Nath-Reddy/XML-XSD-XSLT/xsd.xsd
<xs:element name="snap_n_stick">
        <xs:complexType>
            <xs:sequence>
    <xs:element name="customers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="customer" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CustomerID">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="100000"/>
                                    <xs:maxInclusive value="1000000000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="firstname" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="phone" type="xs:integer"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                            <xs:element name="state" type="xs:string"/>
                            <xs:element name="zipcode" type="xs:integer"/>
                            <xs:element name="registrationdate" type="xs:dateTime"/>    
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <!-- Define the orders element -->
    <xs:element name="orders">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="order" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="orderID" type="xs:integer"/>
                            <xs:element name="customerID" type="xs:string"/>
                            <xs:element name="orderdate" type="xs:dateTime"/>
                            <xs:element name="totalamount" type="xs:decimal"/>
                            <xs:element name="paymentstatus" type="xs:string"/>
                            <xs:element name="shipmentstatus" type="xs:string"/>
                            <xs:element name="shippingaddress" type="xs:string"/>
                            <xs:element name="billingaddress" type="xs:string"/>
                            <xs:element name="discountcode" type="xs:string"/>
                            <xs:element name="taxamount">
                            <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0.0"/>
                                    <xs:maxInclusive value="1000.0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>  
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

=== Hema-Nath-Reddy/XML-XSD-XSLT/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xslt.xsl"?>
<snap_n_stick xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="xsd.xsd">
<customers>
    <customer>
        <CustomerID>123456789</CustomerID>
        <firstname>John</firstname>
        <lastname>Doe</lastname>
        <email>john.doe@example.com</email>
        <phone>1234567890</phone>
        <address>123 main street</address>
        <city>anytown city</city>
        <state>AP</state>
        <zipcode>500016</zipcode>
        <registrationdate>2024-02-03 10:09:50</registrationdate>
    </customer>
    <customer>
        <CustomerID>312423432</CustomerID>
        <firstname>Doe</firstname>
        <lastname>John</lastname>
        <email>Doe.john@example.com</email>
        <phone>9876543218</phone>
        <address>456 street</address>
        <city>sometown </city>
        <state>TN</state>
        <zipcode>500018</zipcode>
        <registrationdate>2024-02-09 11:09:50</registrationdate>
    </customer>
    <customer>
        <CustomerID>67465764745</CustomerID>
        <firstname>George</firstname>
        <lastname>Washington</lastname>
        <email>George.Washington@example.com</email>
        <phone>9874562344</phone>
        <address>123 west avenue</address>
        <city>thistown </city>
        <state>TS</state>
        <zipcode>500011</zipcode>
        <registrationdate>2024-02-07 12:09:50</registrationdate>
    </customer>
</customers>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lab10.xsd">
    <order>
        <orderID>2343100</orderID>
        <customerID>34253425</customerID>
        <orderdate>2024-02-03T10:09:50</orderdate>
        <totalamount>249.99</totalamount>
        <paymentstatus>paid</paymentstatus>
        <shipmentstatus>Pending</shipmentstatus>
        <shippingaddress>123 Main Street, Anytown City, AP, 500016</shippingaddress>
        <billingaddress>123 Main Street, Anytown City, AP, 500016</billingaddress>
        <discountcode>None</discountcode>
        <taxamount>5</taxamount>
    </order>
     <order>
        <orderID>2343400</orderID>
        <customerID>456745</customerID>
        <orderdate>2024-02-03T10:09:50</orderdate>
        <totalamount>999.99</totalamount>
        <paymentstatus>paid</paymentstatus>
        <shipmentstatus>Pending</shipmentstatus>
        <shippingaddress>789 Oak Avenue, Another City, TS, 500011</shippingaddress>
        <billingaddress>789 Oak Avenue, Another City, TS, 500011</billingaddress>
        <discountcode>Above500</discountcode>
        <taxamount>20</taxamount>
    </order>
    <order>
        <orderID>2343300</orderID>
        <customerID>45674567</customerID>
        <orderdate>2024-02-03T10:09:50</orderdate>
        <totalamount>499.99</totalamount>
        <paymentstatus>paid</paymentstatus>
        <shipmentstatus>Pending</shipmentstatus>
        <shippingaddress>456 Elm Street, Othertown, TN, 500018</shippingaddress>
        <billingaddress>456 Elm Street, Othertown, TN, 500018</billingaddress>
        <discountcode>None</discountcode>
        <taxamount>10</taxamount>
    </order>
   
</orders>
</snap_n_stick>
